services:
  platform_docker-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jerv-app
    depends_on:
      platform_docker-db:
        condition: service_healthy
    environment:
      APP_ENV: dev
      APP_SECRET: 845231159a18cb841b0b55b08509aa8a
      DATABASE_URL: mysql://${DB_USER}:${DB_PASSWORD}@platform_docker-db:3306/${DB_NAME}?serverVersion=8.4&charset=utf8mb4
    ports:
      - "8080:80"

  platform_docker-db:
    image: mysql:8.4
    container_name: jerv-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "${DB_USER}", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    ports:
      - "3306:3306"
    volumes:
      - platform_docker_db_data:/var/lib/mysql

  platform_docker-phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: jerv-phpmyadmin
    depends_on:
      platform_docker-db:
        condition: service_healthy
    environment:
      PMA_HOST: platform_docker-db
      PMA_PORT: 3306
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8081:80"

volumes:
  platform_docker_db_data: